[package]
name = "game-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
log = "0.4.27"
wgpu = "25.0.2"
winit = { version = "0.29", features = ["android-native-activity"] }
